language: go

go:
  - 1.10.x

services:
  - postgresql
  - redis

before_install:
  - go get -v github.com/caoxiaolin/go-shorturl

before_script:
  - psql -c "CREATE DATABASE shorturl;" -U postgres
  - psql -c "CREATE TABLE url (id bigserial, url character varying, hits bigint, create_time timestamp, last_access_time timestamp, PRIMARY KEY (id));" -U postgres

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
