[server]
host = "127.0.0.1"
port = 4000

[database]
host     = "127.0.0.1"
port   	 = 5432
username = "postgres"
password = ""
dbname   = "shorturl"
maxconn  = 2000

[log]
logpath  = "./log/"
logfile  = "access.log"
