[server]
host = "127.0.0.1"
port = 4000

[database]
host     = "127.0.0.1"
port   	 = 5432
username = "rdtest"
password = "123456"
dbname   = "shorturl"
maxconn  = 2000

[redis]
host     = "127.0.0.1"
port     = 6379
password = ""
database = 0

[log]
logpath  = "./"
logfile  = "access.log"
